# Generated by Django 3.2.12 on 2022-03-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_invitetoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='core.artist'),
        ),
    ]
