# Generated by Django 3.2.12 on 2022-04-04 08:00

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_invitetoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_user_image_path),
        ),
    ]
