# Generated by Django 3.2.12 on 2022-04-07 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220407_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('finished', 'finished'), ('ns', 'not started')], default='ns', max_length=10),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
