# Generated by Django 3.2.12 on 2022-05-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220505_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post',
        ),
        migrations.AddField(
            model_name='order',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
