# Generated by Django 3.2.12 on 2022-05-12 12:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220505_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='cover',
            field=models.ImageField(null=True, upload_to=core.models.upload_post_image_path),
        ),
    ]
