# Generated by Django 3.2.12 on 2022-04-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220407_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='status',
        ),
    ]
