# Generated by Django 3.2.12 on 2022-04-09 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_exhibition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='date',
        ),
        migrations.AddField(
            model_name='auction',
            name='date_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auction',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
