# Generated by Django 3.2.12 on 2022-04-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220409_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, to='core.Artist'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='core.Post'),
        ),
    ]
