# Generated by Django 3.2.12 on 2022-05-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220413_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipped',
            new_name='is_shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
