# Generated by Django 3.2.12 on 2022-05-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_exhibition_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='artist',
        ),
    ]
